
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='xedocs',
    version='0.1.0',
    description='Top-level package for xedocs.',
    python_requires='<3.11,>=3.8',
    project_urls={"homepage": "https://github.com/XENONnT/xedocs"},
    author='Yossi Mosbacher',
    author_email='joe.mosbacher@gmail.com',
    classifiers=['Development Status :: 2 - Pre-Alpha', 'Intended Audience :: Developers', 'Natural Language :: English', 'Programming Language :: Python :: 3.8'],
    entry_points={"console_scripts": ["xedocs = xedocs.cli:main"]},
    packages=['xedocs', 'xedocs.schemas', 'xedocs.schemas.calibrations', 'xedocs.schemas.corrections'],
    package_dir={"": "."},
    package_data={},
    install_requires=['click', 'rframe==0.*,>=0.1.11', 'utilix==0.*,>=0.6.7'],
    extras_require={"dev": ["black==22.*,>=22.1.0", "bumpversion", "coverage", "flake8", "invoke", "isort", "nbsphinx", "pylint", "pytest", "sphinx", "sphinx-material", "tox", "yapf"]},
)
