name: CI

on: [push, pull_request]

jobs:

  run-tests:
    name: Run tests
    strategy:
      matrix:
        os: [Ubuntu]
        python-version: ['3.7', '3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Install poethepoet
        run: pipx install poethepoet

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 4.2

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        env:
          TEST_MONGO_URI: 'mongodb://localhost:27017/'
        run: poe test -v
