name: CI

on: [push, pull_request]

jobs:

  run-tests:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu]
        python-version: [ '3.10', '3.11']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Install poethepoet
        run: pipx install poethepoet

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: 4.4.1

      - name: Run tests
        env:
          TEST_MONGO_URI: 'localhost'
        run: poe test -v
